[package]
name = "dyon"
version = "0.6.1"
authors = ["Sven Nilsen <bvssvni@gmail.com>"]
keywords = ["script", "scripting", "game", "language", "piston"]
description = "A rusty dynamically typed scripting language"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/pistondevelopers/dyon.git"
homepage = "https://github.com/pistondevelopers/dyon"
exclude = ["images/*", "editor-plugins/*"]

[dependencies]
piston_meta = "0.26.1"
range = "0.3.1"
rand = "0.3.13"
read_color = "0.1.0"
hyper = "0.9.4"

[features]
default = ["debug_resolve"]
debug_resolve = []
