[package]
name = "dyon"
version = "0.4.0"
authors = ["Sven Nilsen <bvssvni@gmail.com>"]
keywords = ["script", "scripting", "game", "language", "piston"]
description = "A rusty dynamically typed scripting language"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/dyon.git"
homepage = "https://github.com/pistondevelopers/dyon"
exclude = ["images/*"]

[dependencies]
piston_meta = "0.26.1"
range = "0.3.1"
rand = "0.3.13"

[dev-dependencies]
piston_window = "0.40.0"
current = "0.1.1"
